# Generated by Django 2.1 on 2018-09-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerPage', '0002_auto_20180831_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owners',
            old_name='specifications',
            new_name='cpu',
        ),
        migrations.AddField(
            model_name='owners',
            name='graphic_card',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='owners',
            name='keyboard',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='owners',
            name='main_borad',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='owners',
            name='memory',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='owners',
            name='mouse',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='owners',
            name='ssd',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
