# Generated by Django 2.1 on 2018-09-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerPage', '0003_auto_20180903_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='cpu',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='owners',
            name='graphic_card',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='owners',
            name='keyboard',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='owners',
            name='main_borad',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='owners',
            name='memory',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='owners',
            name='mouse',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='owners',
            name='ssd',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
