# Generated by Django 2.1 on 2018-09-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerPage', '0004_auto_20180903_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owners',
            old_name='main_borad',
            new_name='main_board',
        ),
    ]
